name: The Bot Host
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: clone the project 
        run: git clone https://github.com/ANGILO856122/FORKX
      - name: Install dependencies
        run: rm -rf pakcage-lock.json && npm i
      - name: Start The Code
        run:  npm start &
        
          
      - name: keep alive
        id: check_runs
        run: |
          echo "has_new_run=false" >> $GITHUB_OUTPUT
          while true; do
            sleep 10
            latest_run=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1&status=queued&status=in_progress" | \
              jq -r '.workflow_runs[0].id')
            if [[ $latest_run != ${{ github.run_id }} ]]; then
              echo "has_new_run=true" >> $GITHUB_OUTPUT
              break
            fi
          done
          
      - name: Commit the logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "out session update" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      
      - name: Stop workflow
        if: steps.check_runs.outputs.has_new_run == 'true'
        run: exit 0

      - name: keep
        if: steps.check_runs.outputs.has_new_run == 'false'
        run: sleep 600000000
